VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ubuntusp19"
  # Configure vm name (later used for ansible group)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  # manual ip
  config.vm.network "public_network", ip: "192.168.50.4", bridge: "br-8fcc2215ccb0"
  config.vm.network "forwarded_port", guest: 3389, host: 33390

  config.vm.provision "shell",
    inline: "sudo apt-get update && sudo apt install -y python"
   
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo {ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yml"

    ansible.groups = {
      "test" => ["ubuntusp19"]
    }
  end
end
